//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacketStringManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RacketStringManager.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CreateJob_Comment {
            get {
                return ResourceManager.GetString("CreateJob_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CreateJob_Name {
            get {
                return ResourceManager.GetString("CreateJob_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racket.
        /// </summary>
        internal static string CreateJob_Racket {
            get {
                return ResourceManager.GetString("CreateJob_Racket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CreateJob_Save {
            get {
                return ResourceManager.GetString("CreateJob_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string CreateJob_String {
            get {
                return ResourceManager.GetString("CreateJob_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        internal static string CreateJob_Tension {
            get {
                return ResourceManager.GetString("CreateJob_Tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string CreateJob_Title {
            get {
                return ResourceManager.GetString("CreateJob_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can import and export all jobs. Note that when importing data, all existing data will be deleted and only the imported jobs are available after the import.
        /// </summary>
        internal static string DataManagement_Description {
            get {
                return ResourceManager.GetString("DataManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string DataManagement_ExportButtonText {
            get {
                return ResourceManager.GetString("DataManagement_ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Excel.
        /// </summary>
        internal static string DataManagement_ImportButtonText {
            get {
                return ResourceManager.GetString("DataManagement_ImportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        internal static string DataManagement_Title {
            get {
                return ResourceManager.GetString("DataManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import error in row {0}.
        /// </summary>
        internal static string ExcelImport_ErrorMessage_ErrorInRow {
            get {
                return ResourceManager.GetString("ExcelImport_ErrorMessage_ErrorInRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string ExcelImport_ExceptionPopup_Title {
            get {
                return ResourceManager.GetString("ExcelImport_ExceptionPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ExcelImport_Ok {
            get {
                return ResourceManager.GetString("ExcelImport_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0}/{1}.
        /// </summary>
        internal static string ExcelImport_SuccessPopup_MessageFormat {
            get {
                return ResourceManager.GetString("ExcelImport_SuccessPopup_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Complete.
        /// </summary>
        internal static string ExcelImport_SuccessPopup_Title {
            get {
                return ResourceManager.GetString("ExcelImport_SuccessPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string JobDetails_Comment {
            get {
                return ResourceManager.GetString("JobDetails_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string JobDetails_Completed {
            get {
                return ResourceManager.GetString("JobDetails_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string JobDetails_DeleteConfirm_Accept {
            get {
                return ResourceManager.GetString("JobDetails_DeleteConfirm_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string JobDetails_DeleteConfirm_Cancel {
            get {
                return ResourceManager.GetString("JobDetails_DeleteConfirm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the job?.
        /// </summary>
        internal static string JobDetails_DeleteConfirm_Message {
            get {
                return ResourceManager.GetString("JobDetails_DeleteConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job?.
        /// </summary>
        internal static string JobDetails_DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("JobDetails_DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string JobDetails_DeleteJob {
            get {
                return ResourceManager.GetString("JobDetails_DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string JobDetails_EditJob {
            get {
                return ResourceManager.GetString("JobDetails_EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JobDetails_Name {
            get {
                return ResourceManager.GetString("JobDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string JobDetails_Paid {
            get {
                return ResourceManager.GetString("JobDetails_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racket.
        /// </summary>
        internal static string JobDetails_Racket {
            get {
                return ResourceManager.GetString("JobDetails_Racket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string JobDetails_StartDate {
            get {
                return ResourceManager.GetString("JobDetails_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string JobDetails_String {
            get {
                return ResourceManager.GetString("JobDetails_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        internal static string JobDetails_Tension {
            get {
                return ResourceManager.GetString("JobDetails_Tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Overview_AllJobs {
            get {
                return ResourceManager.GetString("Overview_AllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string Overview_NewJob {
            get {
                return ResourceManager.GetString("Overview_NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Overview_PendingJobs {
            get {
                return ResourceManager.GetString("Overview_PendingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview_Title {
            get {
                return ResourceManager.GetString("Overview_Title", resourceCulture);
            }
        }
    }
}
